# [Medium](https://towardsdatascience.com/implementing-spatial-transformer-network-stn-in-tensorflow-bf0dc5055cd5)

In [8]:
import pandas as pd
import numpy as np

# Essential NumPy Operations

In [9]:
x = np.random.randint(10, size=8)

In [12]:
x.shape

(8,)

In [13]:
x

array([4, 1, 4, 1, 0, 7, 6, 8])

In [11]:
x[[1,2,5]]

array([1, 4, 7])

### 2d array

#### Common Case

In [23]:
x = [
        [0, 1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
]

x = np.asarray(x)

In [24]:
x[2, 3] # row 2, col 3

15

#### Special Case 1

In [38]:
"""
declare a list of rows and a list of columns
then map them together
"""
x = [
        [0, 1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
]

x = np.asarray(x)

x[
    [1,2,3], # row_ls
    [3,2,3], # col_ls
]

# [ x[1, 3], x[2, 2], x[3, 3] ]

array([ 9, 14, 21])

#### Special Case 2

In [39]:
x = [
        [0, 1, 2, 3, 4, 5],
        [6, 7, 8, 9, 10, 11],
        [12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23],
]

x = np.asarray(x)

In [36]:
a = [
        [1,2], 
        [3,0],
]

In [37]:
b = [
        [0,1], 
        [2,3],
]

In [35]:
x[
    a, 
    b,
]

array([[ 6, 13],
       [20,  3]])

## Array Transformation

In [46]:
x = np.asarray([100, 100, 1])
x

array([100, 100,   1])

In [47]:
x.shape

(3,)

In [48]:
theta = np.asarray([[0.5, 0, 0], [0, 0.5, 0]])

In [64]:
x @ theta

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 400)

## Image Transformation

In [52]:
height = 400
width = 400

x and y are selected in the range of -1 to 1, so the the transformation happens <br>
when considering the center of the image as the origin. The images will be later scaled up.

In [53]:
x = np.linspace(-1, 1, width)
y = np.linspace(-1, 1, height)

In [70]:
x.shape, y.shape

((400,), (400,))

In [54]:
x

array([-1.        , -0.99498747, -0.98997494, -0.98496241, -0.97994987,
       -0.97493734, -0.96992481, -0.96491228, -0.95989975, -0.95488722,
       -0.94987469, -0.94486216, -0.93984962, -0.93483709, -0.92982456,
       -0.92481203, -0.9197995 , -0.91478697, -0.90977444, -0.9047619 ,
       -0.89974937, -0.89473684, -0.88972431, -0.88471178, -0.87969925,
       -0.87468672, -0.86967419, -0.86466165, -0.85964912, -0.85463659,
       -0.84962406, -0.84461153, -0.839599  , -0.83458647, -0.82957393,
       -0.8245614 , -0.81954887, -0.81453634, -0.80952381, -0.80451128,
       -0.79949875, -0.79448622, -0.78947368, -0.78446115, -0.77944862,
       -0.77443609, -0.76942356, -0.76441103, -0.7593985 , -0.75438596,
       -0.74937343, -0.7443609 , -0.73934837, -0.73433584, -0.72932331,
       -0.72431078, -0.71929825, -0.71428571, -0.70927318, -0.70426065,
       -0.69924812, -0.69423559, -0.68922306, -0.68421053, -0.67919799,
       -0.67418546, -0.66917293, -0.6641604 , -0.65914787, -0.65

In [55]:
y

array([-1.        , -0.99498747, -0.98997494, -0.98496241, -0.97994987,
       -0.97493734, -0.96992481, -0.96491228, -0.95989975, -0.95488722,
       -0.94987469, -0.94486216, -0.93984962, -0.93483709, -0.92982456,
       -0.92481203, -0.9197995 , -0.91478697, -0.90977444, -0.9047619 ,
       -0.89974937, -0.89473684, -0.88972431, -0.88471178, -0.87969925,
       -0.87468672, -0.86967419, -0.86466165, -0.85964912, -0.85463659,
       -0.84962406, -0.84461153, -0.839599  , -0.83458647, -0.82957393,
       -0.8245614 , -0.81954887, -0.81453634, -0.80952381, -0.80451128,
       -0.79949875, -0.79448622, -0.78947368, -0.78446115, -0.77944862,
       -0.77443609, -0.76942356, -0.76441103, -0.7593985 , -0.75438596,
       -0.74937343, -0.7443609 , -0.73934837, -0.73433584, -0.72932331,
       -0.72431078, -0.71929825, -0.71428571, -0.70927318, -0.70426065,
       -0.69924812, -0.69423559, -0.68922306, -0.68421053, -0.67919799,
       -0.67418546, -0.66917293, -0.6641604 , -0.65914787, -0.65

In [57]:
# 45 degree rotation matrix
transformation_matrix = np.asarray(
    [
        [np.cos(np.pi/4), -np.sin(np.pi/4), 0], 
        [np.sin(np.pi/4), np.cos(np.pi/4),0],
    ]
)

In [58]:
transformation_matrix

array([[ 0.70710678, -0.70710678,  0.        ],
       [ 0.70710678,  0.70710678,  0.        ]])

In [59]:
xx, yy = np.meshgrid(x, y)

In [60]:
xx

array([[-1.        , -0.99498747, -0.98997494, ...,  0.98997494,
         0.99498747,  1.        ],
       [-1.        , -0.99498747, -0.98997494, ...,  0.98997494,
         0.99498747,  1.        ],
       [-1.        , -0.99498747, -0.98997494, ...,  0.98997494,
         0.99498747,  1.        ],
       ...,
       [-1.        , -0.99498747, -0.98997494, ...,  0.98997494,
         0.99498747,  1.        ],
       [-1.        , -0.99498747, -0.98997494, ...,  0.98997494,
         0.99498747,  1.        ],
       [-1.        , -0.99498747, -0.98997494, ...,  0.98997494,
         0.99498747,  1.        ]])

In [61]:
yy

array([[-1.        , -1.        , -1.        , ..., -1.        ,
        -1.        , -1.        ],
       [-0.99498747, -0.99498747, -0.99498747, ..., -0.99498747,
        -0.99498747, -0.99498747],
       [-0.98997494, -0.98997494, -0.98997494, ..., -0.98997494,
        -0.98997494, -0.98997494],
       ...,
       [ 0.98997494,  0.98997494,  0.98997494, ...,  0.98997494,
         0.98997494,  0.98997494],
       [ 0.99498747,  0.99498747,  0.99498747, ...,  0.99498747,
         0.99498747,  0.99498747],
       [ 1.        ,  1.        ,  1.        , ...,  1.        ,
         1.        ,  1.        ]])

In [62]:
homogeneous_co_ordinates = np.vstack([xx.flatten(), yy.flatten(), np.ones_like(xx.flatten())])

In [63]:
homogeneous_co_ordinates.shape

(3, 160000)

In [66]:
# @ for matrix multiplication
transformed_co_ordinates = transformation_matrix @ homogeneous_co_ordinates

In [67]:
transformed_co_ordinates.shape

(2, 160000)

In [68]:
transformed_co_ordinates = transformed_co_ordinates.reshape(2, height, width)

In [69]:
transformed_co_ordinates.shape

(2, 400, 400)

In [71]:
transformed_co_ordinates = np.moveaxis(transformed_co_ordinates, 0, -1)

In [72]:
transformed_co_ordinates.shape

(400, 400, 2)

In [73]:
type(transformed_co_ordinates)

numpy.ndarray

extracting x and the y co-ordinates separately separately

In [76]:
x_transformed = transformed_co_ordinates[:,:,0:1].squeeze()

In [77]:
y_transformed = transformed_co_ordinates[:,:,1:2].squeeze()

In [78]:
x = ((x_transformed + 1.) * width) * 0.5 

In [79]:
y = ((y_transformed + 1.) * height) * 0.5 

In [80]:
x.shape

(400, 400)

In [81]:
y.shape

(400, 400)

In [82]:
x0 = np.floor(x).astype(np.int64)

In [83]:
x1 = x0 + 1